-- Seed directory_entries with rich Ayurvedic data
INSERT INTO directory_entries (
  type, title, slug, sanskrit_name, english_name, meaning, summary, definition, introduction, etiology, 
  synonyms, origin, panchabhautikatva, swaroop, characteristics, types_description, sankhya, 
  prakar_charak, prakar_sushruta, moolasthana, viddha_lakshan, dushti, functions, disorders, 
  treatment_principles, related_course_ids
) VALUES 
(
  'Srotas', 'Pranavaha Srotas', 'pranavaha-srotas', 'प्राणवह स्रोतस्', 'Pranavaha Srotas', 
  'Channels carrying Prana (vital life force)', 
  'The principal respiratory channel system responsible for the movement of Prana Vayu throughout the body.',
  'Pranavaha Srotas refers to the channels through which Prana Vayu — the vital breath and life energy — circulates throughout the body.',
  'Pranavaha Srotas are the vital channels that carry "Prana" (the life force or vital breath).',
  'The vitiation of Pranavaha Srotas is caused by: 1. Consumption of dry, cold, and light food.',
  ARRAY['Srotamsi', 'Sirah'],
  'According to Ayurvedic embryology, Srotas originate during fetal development.',
  'Srotas are predominantly composed of the Akasha Mahabhuta.',
  'Srotas are described as matching the color of the tissue they carry.',
  ARRAY['Vritta (Circular/Round)', 'Sthula (Thick/Gross)'],
  'Srotas are broadly classified into two types: Bahirmukha and Yogavahi.',
  'Acharya Charaka mentions 13 pairs of internal Srotas.',
  'Pranavaha, Udakavaha, Annavaha, Rasavaha, Raktavaha...',
  'Similar to Charaka but differs by excluding Asthi, Majja...',
  'Hridaya (Heart) and Mahasrotas',
  'When Pranavaha Srotas is injured it leads to disturbed breathing.',
  'Symptoms of Srotas Dushti: Atisrushta, Atibaddha...',
  ARRAY['Transports Prana Vayu throughout the body', 'Coordinates respiratory movements'],
  ARRAY['Shvasa (Dyspnea / Asthma)', 'Kasa (Cough)'],
  ARRAY['Pranayama and breathing exercises', 'Vamana'],
  ARRAY[]::uuid[]
),
(
  'Srotas', 'Rasavaha Srotas', 'rasavaha-srotas', 'रसवह स्रोतस्', 'Rasavaha Srotas', 
  'Channels carrying Rasa Dhatu (plasma/nutrient fluid)', 
  'The nutritive channel system responsible for circulation of Rasa Dhatu and post-digestive nutrient absorption.',
  'Rasavaha Srotas are the channels through which Rasa Dhatu flows and nourishes the entire body.',
  'Foundation of the nutritive circulatory system.',
  'Vitiated by heavy, cold, and incompatible food.',
  ARRAY['Rasavahini'],
  'Embryological origin from the heart.',
  'Predominantly Jala and Akasha Mahabhuta.',
  'Cylindrical and matching the color of nutrient plasma.',
  ARRAY['Liquid', 'Nutritive'],
  'Foundation of all tissue circulation.',
  'Originate from the heart and ten vessels.',
  'Rasavaha',
  'Yogavahi',
  'Hridaya and Dasha Dhamanis',
  'Heart palpitations and anemia upon injury.',
  'Loss of appetite, fever, and pallor.',
  ARRAY['Transports nutrient fluid', 'Nourishes all tissues'],
  ARRAY['Aruci (Anorexia)', 'Fever'],
  ARRAY['Digestive stimulants', 'Rejuvenation'],
  ARRAY[]::uuid[]
),
(
  'Dosha', 'Vata Dosha', 'vata-dosha', 'वात दोष', 'Vata Dosha', 
  'The regulatory bioenergy governing movement and space', 
  'Vata is the kinetic biological force composed of Akasha (space) and Vayu (air) elements.',
  'Kinetic force of the body.',
  'Governs all biological movement.',
  'Aggravated by dry, cold, and light qualities.',
  ARRAY['Vayu', 'Anila'],
  'Primary bio-energy.',
  'Akasha and Vayu.',
  'Subtle and non-manifest.',
  ARRAY['Dry', 'Cold', 'Light', 'Mobile', 'Subtle', 'Clear', 'Rough'],
  'Five types of Vayu.',
  'One fundamental Dosha with five sub-types.',
  'Vata',
  'Vata',
  'Pakwashaya (Colon)',
  'Pain and tremors.',
  'Dryness, coldness, tremors.',
  ARRAY['Governs movement', 'Controls respiration'],
  ARRAY['Pain', 'Constipation', 'Anxiety'],
  ARRAY['Oleation', 'Basti (Enema)', 'Warmth'],
  ARRAY[]::uuid[]
),
(
  'Dosha', 'Pitta Dosha', 'pitta-dosha', 'पित्त दोष', 'Pitta Dosha', 
  'The transformative bioenergy governing metabolism and digestion', 
  'Pitta is the metabolic biological force composed of Agni (fire) and Jala (water) elements.',
  'Transformative force of the body.',
  'Governs all biochemical transformations.',
  'Aggravated by hot, sharp, and spicy qualities.',
  ARRAY['Tejas', 'Agni'],
  'Primary digestive energy.',
  'Agni and Jala.',
  'Liquid and hot.',
  ARRAY['Hot', 'Sharp', 'Light', 'Oily', 'Liquid', 'Spreading'],
  'Five types of Pitta.',
  'One fundamental Dosha with five sub-types.',
  'Pitta',
  'Pitta',
  'Nabhi (Small Intestine)',
  'Burning sensations and inflammation.',
  'Heat, redness, anger.',
  ARRAY['Governs digestion', 'Maintains temperature'],
  ARRAY['Inflammation', 'Acidity', 'Fever'],
  ARRAY['Purgation (Virechana)', 'Cooling herbs'],
  ARRAY[]::uuid[]
),
(
  'Dosha', 'Kapha Dosha', 'kapha-dosha', 'कफ दोष', 'Kapha Dosha', 
  'The structural bioenergy governing stability and cohesion', 
  'Kapha is the anabolic biological force composed of Prithvi (earth) and Jala (water) elements.',
  'Structural force of the body.',
  'Provides stability and lubrication.',
  'Aggravated by heavy, cold, and sweet qualities.',
  ARRAY['Shleshma'],
  'Primary structural energy.',
  'Prithvi and Jala.',
  'Heavy, stable, and slimy.',
  ARRAY['Heavy', 'Cold', 'Soft', 'Oily', 'Sweet', 'Stable', 'Slimy'],
  'Five types of Kapha.',
  'One fundamental Dosha with five sub-types.',
  'Kapha',
  'Kapha',
  'Uras (Chest)',
  'Congestion and sluggishness.',
  'Heaviness, coldness, lethargy.',
  ARRAY['Provides structure', 'Lubricates joints'],
  ARRAY['Obesity', 'Congestion', 'Lethargy'],
  ARRAY['Emesis (Vamana)', 'Activity', 'Warmth'],
  ARRAY[]::uuid[]
),
(
  'Herbs', 'Ashwagandha', 'ashwagandha', 'अश्वगन्धा', 'Ashwagandha', 
  'Smell of horse — imparts the strength and vitality of a horse', 
  'The most revered adaptogenic herb in Ayurveda, known as the "King of Herbs".',
  'Adaptogenic and rejuvenating herb.',
  'Medhya Rasayana for brain and body.',
  'Vata-Kapha pacifying.',
  ARRAY['Winter Cherry', 'Withania somnifera'],
  'Grows in dry regions of India.',
  'Prithvi and Vayu.',
  'Shrub with fleshy roots.',
  ARRAY['Rejuvenating', 'Strengthening'],
  'Classified as Rasayana.',
  'Medhya, Balya, Vajikara.',
  'Ashwagandha',
  'Ashwagandha',
  'Roots',
  'Loss of energy.',
  'Weakness and stress.',
  ARRAY['Reduces stress', 'Improves vitality'],
  ARRAY['Anxiety', 'Fatigue', 'Insomnia'],
  ARRAY['Classic dose with milk', 'Rasayana therapy'],
  ARRAY[]::uuid[]
)
ON CONFLICT (slug) DO NOTHING;
